// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_tinypb_server.proto

package com.iker.tinyrpc.proto;

public interface queryNameReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:queryNameReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 req_no = 1;</code>
   * @return The reqNo.
   */
  int getReqNo();

  /**
   * <code>int32 id = 2;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>int32 type = 3;</code>
   * @return The type.
   */
  int getType();
}
