// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_tinypb_server.proto

package com.iker.tinyrpc.proto;

/**
 * Protobuf type {@code queryAgeRes}
 */
public final class queryAgeRes extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:queryAgeRes)
    queryAgeResOrBuilder {
private static final long serialVersionUID = 0L;
  // Use queryAgeRes.newBuilder() to construct.
  private queryAgeRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private queryAgeRes() {
    resInfo_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new queryAgeRes();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private queryAgeRes(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            retCode_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            resInfo_ = s;
            break;
          }
          case 24: {

            reqNo_ = input.readInt32();
            break;
          }
          case 32: {

            id_ = input.readInt32();
            break;
          }
          case 40: {

            age_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.iker.tinyrpc.proto.TestTinypbServer.internal_static_queryAgeRes_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.iker.tinyrpc.proto.TestTinypbServer.internal_static_queryAgeRes_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.iker.tinyrpc.proto.queryAgeRes.class, com.iker.tinyrpc.proto.queryAgeRes.Builder.class);
  }

  public static final int RET_CODE_FIELD_NUMBER = 1;
  private int retCode_;
  /**
   * <code>int32 ret_code = 1;</code>
   * @return The retCode.
   */
  @java.lang.Override
  public int getRetCode() {
    return retCode_;
  }

  public static final int RES_INFO_FIELD_NUMBER = 2;
  private volatile java.lang.Object resInfo_;
  /**
   * <code>string res_info = 2;</code>
   * @return The resInfo.
   */
  @java.lang.Override
  public java.lang.String getResInfo() {
    java.lang.Object ref = resInfo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      resInfo_ = s;
      return s;
    }
  }
  /**
   * <code>string res_info = 2;</code>
   * @return The bytes for resInfo.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getResInfoBytes() {
    java.lang.Object ref = resInfo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      resInfo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REQ_NO_FIELD_NUMBER = 3;
  private int reqNo_;
  /**
   * <code>int32 req_no = 3;</code>
   * @return The reqNo.
   */
  @java.lang.Override
  public int getReqNo() {
    return reqNo_;
  }

  public static final int ID_FIELD_NUMBER = 4;
  private int id_;
  /**
   * <code>int32 id = 4;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int AGE_FIELD_NUMBER = 5;
  private int age_;
  /**
   * <code>int32 age = 5;</code>
   * @return The age.
   */
  @java.lang.Override
  public int getAge() {
    return age_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (retCode_ != 0) {
      output.writeInt32(1, retCode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(resInfo_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, resInfo_);
    }
    if (reqNo_ != 0) {
      output.writeInt32(3, reqNo_);
    }
    if (id_ != 0) {
      output.writeInt32(4, id_);
    }
    if (age_ != 0) {
      output.writeInt32(5, age_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (retCode_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, retCode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(resInfo_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, resInfo_);
    }
    if (reqNo_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, reqNo_);
    }
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, id_);
    }
    if (age_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, age_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.iker.tinyrpc.proto.queryAgeRes)) {
      return super.equals(obj);
    }
    com.iker.tinyrpc.proto.queryAgeRes other = (com.iker.tinyrpc.proto.queryAgeRes) obj;

    if (getRetCode()
        != other.getRetCode()) return false;
    if (!getResInfo()
        .equals(other.getResInfo())) return false;
    if (getReqNo()
        != other.getReqNo()) return false;
    if (getId()
        != other.getId()) return false;
    if (getAge()
        != other.getAge()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RET_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getRetCode();
    hash = (37 * hash) + RES_INFO_FIELD_NUMBER;
    hash = (53 * hash) + getResInfo().hashCode();
    hash = (37 * hash) + REQ_NO_FIELD_NUMBER;
    hash = (53 * hash) + getReqNo();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + AGE_FIELD_NUMBER;
    hash = (53 * hash) + getAge();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.iker.tinyrpc.proto.queryAgeRes parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iker.tinyrpc.proto.queryAgeRes parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iker.tinyrpc.proto.queryAgeRes parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iker.tinyrpc.proto.queryAgeRes parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iker.tinyrpc.proto.queryAgeRes parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iker.tinyrpc.proto.queryAgeRes parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iker.tinyrpc.proto.queryAgeRes parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.iker.tinyrpc.proto.queryAgeRes parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.iker.tinyrpc.proto.queryAgeRes parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.iker.tinyrpc.proto.queryAgeRes parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.iker.tinyrpc.proto.queryAgeRes parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.iker.tinyrpc.proto.queryAgeRes parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.iker.tinyrpc.proto.queryAgeRes prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code queryAgeRes}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:queryAgeRes)
      com.iker.tinyrpc.proto.queryAgeResOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.iker.tinyrpc.proto.TestTinypbServer.internal_static_queryAgeRes_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.iker.tinyrpc.proto.TestTinypbServer.internal_static_queryAgeRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.iker.tinyrpc.proto.queryAgeRes.class, com.iker.tinyrpc.proto.queryAgeRes.Builder.class);
    }

    // Construct using com.iker.tinyrpc.proto.queryAgeRes.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      retCode_ = 0;

      resInfo_ = "";

      reqNo_ = 0;

      id_ = 0;

      age_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.iker.tinyrpc.proto.TestTinypbServer.internal_static_queryAgeRes_descriptor;
    }

    @java.lang.Override
    public com.iker.tinyrpc.proto.queryAgeRes getDefaultInstanceForType() {
      return com.iker.tinyrpc.proto.queryAgeRes.getDefaultInstance();
    }

    @java.lang.Override
    public com.iker.tinyrpc.proto.queryAgeRes build() {
      com.iker.tinyrpc.proto.queryAgeRes result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.iker.tinyrpc.proto.queryAgeRes buildPartial() {
      com.iker.tinyrpc.proto.queryAgeRes result = new com.iker.tinyrpc.proto.queryAgeRes(this);
      result.retCode_ = retCode_;
      result.resInfo_ = resInfo_;
      result.reqNo_ = reqNo_;
      result.id_ = id_;
      result.age_ = age_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.iker.tinyrpc.proto.queryAgeRes) {
        return mergeFrom((com.iker.tinyrpc.proto.queryAgeRes)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.iker.tinyrpc.proto.queryAgeRes other) {
      if (other == com.iker.tinyrpc.proto.queryAgeRes.getDefaultInstance()) return this;
      if (other.getRetCode() != 0) {
        setRetCode(other.getRetCode());
      }
      if (!other.getResInfo().isEmpty()) {
        resInfo_ = other.resInfo_;
        onChanged();
      }
      if (other.getReqNo() != 0) {
        setReqNo(other.getReqNo());
      }
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (other.getAge() != 0) {
        setAge(other.getAge());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.iker.tinyrpc.proto.queryAgeRes parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.iker.tinyrpc.proto.queryAgeRes) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int retCode_ ;
    /**
     * <code>int32 ret_code = 1;</code>
     * @return The retCode.
     */
    @java.lang.Override
    public int getRetCode() {
      return retCode_;
    }
    /**
     * <code>int32 ret_code = 1;</code>
     * @param value The retCode to set.
     * @return This builder for chaining.
     */
    public Builder setRetCode(int value) {
      
      retCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 ret_code = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRetCode() {
      
      retCode_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object resInfo_ = "";
    /**
     * <code>string res_info = 2;</code>
     * @return The resInfo.
     */
    public java.lang.String getResInfo() {
      java.lang.Object ref = resInfo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resInfo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string res_info = 2;</code>
     * @return The bytes for resInfo.
     */
    public com.google.protobuf.ByteString
        getResInfoBytes() {
      java.lang.Object ref = resInfo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string res_info = 2;</code>
     * @param value The resInfo to set.
     * @return This builder for chaining.
     */
    public Builder setResInfo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      resInfo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string res_info = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearResInfo() {
      
      resInfo_ = getDefaultInstance().getResInfo();
      onChanged();
      return this;
    }
    /**
     * <code>string res_info = 2;</code>
     * @param value The bytes for resInfo to set.
     * @return This builder for chaining.
     */
    public Builder setResInfoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      resInfo_ = value;
      onChanged();
      return this;
    }

    private int reqNo_ ;
    /**
     * <code>int32 req_no = 3;</code>
     * @return The reqNo.
     */
    @java.lang.Override
    public int getReqNo() {
      return reqNo_;
    }
    /**
     * <code>int32 req_no = 3;</code>
     * @param value The reqNo to set.
     * @return This builder for chaining.
     */
    public Builder setReqNo(int value) {
      
      reqNo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 req_no = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearReqNo() {
      
      reqNo_ = 0;
      onChanged();
      return this;
    }

    private int id_ ;
    /**
     * <code>int32 id = 4;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 4;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private int age_ ;
    /**
     * <code>int32 age = 5;</code>
     * @return The age.
     */
    @java.lang.Override
    public int getAge() {
      return age_;
    }
    /**
     * <code>int32 age = 5;</code>
     * @param value The age to set.
     * @return This builder for chaining.
     */
    public Builder setAge(int value) {
      
      age_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 age = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearAge() {
      
      age_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:queryAgeRes)
  }

  // @@protoc_insertion_point(class_scope:queryAgeRes)
  private static final com.iker.tinyrpc.proto.queryAgeRes DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.iker.tinyrpc.proto.queryAgeRes();
  }

  public static com.iker.tinyrpc.proto.queryAgeRes getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<queryAgeRes>
      PARSER = new com.google.protobuf.AbstractParser<queryAgeRes>() {
    @java.lang.Override
    public queryAgeRes parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new queryAgeRes(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<queryAgeRes> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<queryAgeRes> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.iker.tinyrpc.proto.queryAgeRes getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

