// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_tinypb_server.proto

package com.iker.tinyrpc.proto;

public interface queryAgeResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:queryAgeRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 ret_code = 1;</code>
   * @return The retCode.
   */
  int getRetCode();

  /**
   * <code>string res_info = 2;</code>
   * @return The resInfo.
   */
  java.lang.String getResInfo();
  /**
   * <code>string res_info = 2;</code>
   * @return The bytes for resInfo.
   */
  com.google.protobuf.ByteString
      getResInfoBytes();

  /**
   * <code>int32 req_no = 3;</code>
   * @return The reqNo.
   */
  int getReqNo();

  /**
   * <code>int32 id = 4;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>int32 age = 5;</code>
   * @return The age.
   */
  int getAge();
}
