// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_tinypb_server.proto

package com.iker.tinyrpc.proto;

public interface queryAgeReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:queryAgeReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 req_no = 1;</code>
   * @return The reqNo.
   */
  int getReqNo();

  /**
   * <code>int32 id = 2;</code>
   * @return The id.
   */
  int getId();
}
