// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_tinypb_server.proto

package com.iker.tinyrpc.proto;

public interface queryNameResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:queryNameRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 ret_code = 1;</code>
   * @return The retCode.
   */
  int getRetCode();

  /**
   * <code>string res_info = 2;</code>
   * @return The resInfo.
   */
  java.lang.String getResInfo();
  /**
   * <code>string res_info = 2;</code>
   * @return The bytes for resInfo.
   */
  com.google.protobuf.ByteString
      getResInfoBytes();

  /**
   * <code>int32 req_no = 3;</code>
   * @return The reqNo.
   */
  int getReqNo();

  /**
   * <code>int32 id = 4;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string name = 5;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 5;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
