// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_tinypb_server.proto

package com.iker.tinyrpc.proto;

public final class TestTinypbServer {
  private TestTinypbServer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_queryAgeReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_queryAgeReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_queryAgeRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_queryAgeRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_queryNameReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_queryNameReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_queryNameRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_queryNameRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030test_tinypb_server.proto\")\n\013queryAgeRe" +
      "q\022\016\n\006req_no\030\001 \001(\005\022\n\n\002id\030\002 \001(\005\"Z\n\013queryAg" +
      "eRes\022\020\n\010ret_code\030\001 \001(\005\022\020\n\010res_info\030\002 \001(\t" +
      "\022\016\n\006req_no\030\003 \001(\005\022\n\n\002id\030\004 \001(\005\022\013\n\003age\030\005 \001(" +
      "\005\"8\n\014queryNameReq\022\016\n\006req_no\030\001 \001(\005\022\n\n\002id\030" +
      "\002 \001(\005\022\014\n\004type\030\003 \001(\005\"\\\n\014queryNameRes\022\020\n\010r" +
      "et_code\030\001 \001(\005\022\020\n\010res_info\030\002 \001(\t\022\016\n\006req_n" +
      "o\030\003 \001(\005\022\n\n\002id\030\004 \001(\005\022\014\n\004name\030\005 \001(\t2c\n\014Que" +
      "ryService\022*\n\nquery_name\022\r.queryNameReq\032\r" +
      ".queryNameRes\022\'\n\tquery_age\022\014.queryAgeReq" +
      "\032\014.queryAgeResB \n\026com.iker.tinyrpc.proto" +
      "P\001\200\001\001\210\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_queryAgeReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_queryAgeReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_queryAgeReq_descriptor,
        new java.lang.String[] { "ReqNo", "Id", });
    internal_static_queryAgeRes_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_queryAgeRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_queryAgeRes_descriptor,
        new java.lang.String[] { "RetCode", "ResInfo", "ReqNo", "Id", "Age", });
    internal_static_queryNameReq_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_queryNameReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_queryNameReq_descriptor,
        new java.lang.String[] { "ReqNo", "Id", "Type", });
    internal_static_queryNameRes_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_queryNameRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_queryNameRes_descriptor,
        new java.lang.String[] { "RetCode", "ResInfo", "ReqNo", "Id", "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
